nums = [1, 2, 3, 4]
print(nums)
nums.remove(3)
print(nums)
nums.pop()
print(nums)
nums.pop(0)
print(nums)
nums.extend([3, 4])
print(nums)
nums.insert(0, 1)
print(nums)

phrase = "Don't panic!"
plist = list(phrase)
print(phrase)
print(plist)
# for i in range(4):
#     plist.pop()
# plist.pop(0)
# plist.remove("'")
# plist.extend([plist.pop(), plist.pop()])
# plist.insert(2, plist.pop(3))
# new_phrase = ''.join(plist)
new_phrase = ''.join(plist[1:3])
new_phrase = new_phrase + ''.join([plist[5], plist[4], plist[7], plist[6]])
print(plist)
print(new_phrase)

letters = list(phrase)
print(letters[0:10:3])
print(letters[3:])
print(letters[:10])
print(letters[::2])
print(letters[0:3])
print(''.join(letters[0:5]))
print(''.join(letters[-6:]))
print(''.join(letters[::-1]))
print(''.join(letters[::2]))
print(''.join(letters[6:11]))
print(''.join(letters[10:5:-1]))
